[0.063s] Invoking command in '/home/rishith/MRT/MRT_ASSIGNMENT_4/build/custom_msgs': /usr/bin/cmake /home/rishith/MRT/MRT_ASSIGNMENT_4/src/custom_msgs -DCMAKE_INSTALL_PREFIX=/home/rishith/MRT/MRT_ASSIGNMENT_4/install/custom_msgs
[0.074s] -- Found ament_cmake: 1.3.8 (/opt/ros/humble/share/ament_cmake/cmake)
[0.180s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.181s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.182s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.207s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.227s] -- Found sensor_msgs: 4.2.3 (/opt/ros/humble/share/sensor_msgs/cmake)
[0.371s] -- Found cv_bridge: 3.2.1 (/opt/ros/humble/share/cv_bridge/cmake)
[0.501s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.501s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.501s]   custom_msgs --arguments-file
[0.501s]   /home/rishith/MRT/MRT_ASSIGNMENT_4/build/custom_msgs/rosidl_adapter__arguments__custom_msgs.json
[0.501s]   --output-dir
[0.501s]   /home/rishith/MRT/MRT_ASSIGNMENT_4/build/custom_msgs/rosidl_adapter/custom_msgs
[0.501s]   --output-file
[0.501s]   /home/rishith/MRT/MRT_ASSIGNMENT_4/build/custom_msgs/rosidl_adapter/custom_msgs.idls)
[0.501s]   returned error code 1:
[0.501s] 
[0.501s]   Traceback (most recent call last):
[0.502s] 
[0.502s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.502s]       return _run_code(code, main_globals, None,
[0.502s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.502s]       exec(code, run_globals)
[0.502s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.502s]       sys.exit(main())
[0.502s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.502s]       abs_idl_file = convert_to_idl(
[0.502s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[0.502s]       return convert_srv_to_idl(
[0.502s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[0.502s]       srv = parse_service_string(package_name, input_file.stem, content)
[0.503s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 859, in parse_service_string
[0.503s]       request_message = parse_message_string(
[0.503s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[0.503s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[0.503s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[0.503s]       self.base_type = BaseType(
[0.503s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.503s]       raise InvalidResourceName(
[0.503s] 
[0.503s]   rosidl_adapter.parser.InvalidResourceName: 'corners_Request' is an invalid
[0.503s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.503s] 
[0.503s] Call Stack (most recent call first):
[0.503s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.504s]   CMakeLists.txt:20 (rosidl_generate_interfaces)
[0.504s] 
[0.504s] [0m
[0.504s] -- Configuring incomplete, errors occurred!
[0.504s] See also "/home/rishith/MRT/MRT_ASSIGNMENT_4/build/custom_msgs/CMakeFiles/CMakeOutput.log".
[0.505s] Invoked command in '/home/rishith/MRT/MRT_ASSIGNMENT_4/build/custom_msgs' returned '1': /usr/bin/cmake /home/rishith/MRT/MRT_ASSIGNMENT_4/src/custom_msgs -DCMAKE_INSTALL_PREFIX=/home/rishith/MRT/MRT_ASSIGNMENT_4/install/custom_msgs
